# Generated by Django 3.1.6 on 2021-05-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinformation',
            name='Phone',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
