# Generated by Django 3.1.6 on 2021-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, unique=True)),
                ('Desc', models.TextField()),
                ('Teacher_name', models.CharField(max_length=64)),
                ('Teaching_assistant_name', models.CharField(max_length=64)),
                ('Schedule', models.DateField()),
                ('Prerequisite', models.TextField()),
                ('Max_number_of_students', models.CharField(max_length=2)),
                ('Permanent_zoom_meeting_links', models.URLField()),
            ],
        ),
    ]
