# Generated by Django 3.1.6 on 2021-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes_Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_ID', models.CharField(max_length=64)),
                ('Title', models.CharField(max_length=255, unique=True)),
                ('Desc', models.TextField()),
                ('Teacher_name', models.CharField(max_length=64)),
                ('Teaching_assistant_name', models.CharField(max_length=64)),
                ('Schedule', models.DateField()),
                ('Prerequisite', models.TextField()),
                ('Max_number_of_students', models.CharField(max_length=2)),
                ('Permanent_zoom_meeting_links', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='Class_ID',
            field=models.CharField(default=64, max_length=64),
            preserve_default=False,
        ),
    ]
