# Generated by Django 3.1.6 on 2021-03-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('notif_time', models.DateTimeField()),
                ('Classification', models.CharField(choices=[('Important', 'Important'), ('URGENT', 'Urgent'), ('FYI', 'For Your Information')], max_length=10)),
            ],
        ),
    ]
